<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class CurrenciesTableSeeder extends Seeder
{
    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        if (\DB::table('currencies')->count() == 0) {
            \DB::table('currencies')->delete();

            \DB::table('currencies')->insert([
                0 => [
                    'id' => 1,
                    'name' => 'U.S. Dollar',
                    'symbol' => '$',
                    'status' => 1,
                    'code' => 'USD',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2018-10-17 08:50:52',
                ],
                1 => [
                    'id' => 2,
                    'name' => 'Australian Dollar',
                    'symbol' => '$',
                    'status' => 0,
                    'code' => 'AUD',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2021-04-08 13:00:19',
                ],
                2 => [
                    'id' => 5,
                    'name' => 'Brazilian Real',
                    'symbol' => 'R$',
                    'status' => 0,
                    'code' => 'BRL',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2021-04-08 13:00:19',
                ],
                3 => [
                    'id' => 6,
                    'name' => 'Canadian Dollar',
                    'symbol' => '$',
                    'status' => 0,
                    'code' => 'CAD',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2021-04-08 13:00:20',
                ],
                4 => [
                    'id' => 7,
                    'name' => 'Czech Koruna',
                    'symbol' => 'Kč',
                    'status' => 0,
                    'code' => 'CZK',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2021-04-08 13:00:21',
                ],
                5 => [
                    'id' => 8,
                    'name' => 'Danish Krone',
                    'symbol' => 'kr',
                    'status' => 0,
                    'code' => 'DKK',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2021-04-08 13:00:22',
                ],
                6 => [
                    'id' => 9,
                    'name' => 'Euro',
                    'symbol' => '€',
                    'status' => 1,
                    'code' => 'EUR',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2018-10-09 14:35:08',
                ],
                7 => [
                    'id' => 10,
                    'name' => 'Hong Kong Dollar',
                    'symbol' => '$',
                    'status' => 0,
                    'code' => 'HKD',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2021-04-08 13:00:24',
                ],
                8 => [
                    'id' => 11,
                    'name' => 'Hungarian Forint',
                    'symbol' => 'Ft',
                    'status' => 0,
                    'code' => 'HUF',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2021-04-08 13:00:24',
                ],
                9 => [
                    'id' => 12,
                    'name' => 'Israeli New Sheqel',
                    'symbol' => '₪',
                    'status' => 0,
                    'code' => 'ILS',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2021-04-08 13:00:33',
                ],
                10 => [
                    'id' => 13,
                    'name' => 'Japanese Yen',
                    'symbol' => '¥',
                    'status' => 0,
                    'code' => 'JPY',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2021-04-08 13:00:33',
                ],
                11 => [
                    'id' => 14,
                    'name' => 'Malaysian Ringgit',
                    'symbol' => 'RM',
                    'status' => 0,
                    'code' => 'MYR',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2021-04-08 13:00:34',
                ],
                12 => [
                    'id' => 15,
                    'name' => 'Mexican Peso',
                    'symbol' => '$',
                    'status' => 0,
                    'code' => 'MXN',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2021-04-08 13:00:35',
                ],
                13 => [
                    'id' => 16,
                    'name' => 'Norwegian Krone',
                    'symbol' => 'kr',
                    'status' => 0,
                    'code' => 'NOK',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2021-04-08 13:00:36',
                ],
                14 => [
                    'id' => 17,
                    'name' => 'New Zealand Dollar',
                    'symbol' => '$',
                    'status' => 0,
                    'code' => 'NZD',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2021-04-08 13:00:36',
                ],
                15 => [
                    'id' => 18,
                    'name' => 'Philippine Peso',
                    'symbol' => '₱',
                    'status' => 0,
                    'code' => 'PHP',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2021-04-08 13:00:36',
                ],
                16 => [
                    'id' => 19,
                    'name' => 'Polish Zloty',
                    'symbol' => 'zł',
                    'status' => 0,
                    'code' => 'PLN',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2021-04-08 13:00:37',
                ],
                17 => [
                    'id' => 20,
                    'name' => 'Pound Sterling',
                    'symbol' => '£',
                    'status' => 0,
                    'code' => 'GBP',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2021-04-08 13:00:37',
                ],
                18 => [
                    'id' => 21,
                    'name' => 'Russian Ruble',
                    'symbol' => 'руб',
                    'status' => 0,
                    'code' => 'RUB',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2021-04-08 13:00:38',
                ],
                19 => [
                    'id' => 22,
                    'name' => 'Singapore Dollar',
                    'symbol' => '$',
                    'status' => 0,
                    'code' => 'SGD',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2021-04-08 13:00:50',
                ],
                20 => [
                    'id' => 23,
                    'name' => 'Swedish Krona',
                    'symbol' => 'kr',
                    'status' => 0,
                    'code' => 'SEK',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2021-04-08 13:00:51',
                ],
                21 => [
                    'id' => 24,
                    'name' => 'Swiss Franc',
                    'symbol' => 'CHF',
                    'status' => 0,
                    'code' => 'CHF',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2021-04-08 13:00:52',
                ],
                22 => [
                    'id' => 26,
                    'name' => 'Thai Baht',
                    'symbol' => '฿',
                    'status' => 0,
                    'code' => 'THB',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2021-04-08 13:00:53',
                ],
                23 => [
                    'id' => 27,
                    'name' => 'Taka',
                    'symbol' => '৳',
                    'status' => 0,
                    'code' => 'BDT',
                    'created_at' => '2018-10-09 14:35:08',
                    'updated_at' => '2021-04-08 13:00:54',
                ],
                24 => [
                    'id' => 28,
                    'name' => 'Indian Rupee',
                    'symbol' => 'Rs',
                    'status' => 0,
                    'code' => 'Rupee',
                    'created_at' => '2019-07-07 13:33:46',
                    'updated_at' => '2021-04-08 13:00:18',
                ],
            ]);
        }
    }
}
