<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {

        if (\DB::table('products')->count() == 0) {
            \DB::table('products')->delete();

            \DB::table('products')->insert(array(
                0 =>
                    array(
                        'id' => 1,
                        'name' => 'B2BWood',
                        'added_by' => 'admin',
                        'user_id' => 1,
                        'category_id' => 5,
                        'subcategory_id' => NULL,
                        'subsubcategory_id' => NULL,
                        'brand_id' => 1,
                        'photos' => '5,7,6,3',
                        'thumbnail_img' => '1',
                        'video_provider' => 'vimeo',
                        'video_link' => 'https://google.com',
                        'tags' => 'labas',
                        'description' => '<p>Lorem Ipsum, Lorem Ipsum, Lorem Ipsum, Lorem Ipsum, Lorem Ipsum, Lorem Ipsum<br></p>',
                        'unit_price' => 33.0,
                        'purchase_price' => 98.0,
                        'variant_product' => 1,
                        'attributes' => '["2"]',
                        'choice_options' => '[{"attribute_id":"2","values":["Labas"]}]',
                        'colors' => '["#9966CC"]',
                        'variations' => NULL,
                        'todays_deal' => 1,
                        'published' => 1,
                        'stock_visibility_state' => 'quantity',
                        'cash_on_delivery' => 1,
                        'featured' => 1,
                        'seller_featured' => 0,
                        'current_stock' => 23,
                        'unit' => 'Officia laborum Aut',
                        'min_qty' => 79,
                        'low_stock_quantity' => 954,
                        'discount' => 89.0,
                        'discount_type' => 'percent',
                        'tax' => NULL,
                        'tax_type' => NULL,
                        'shipping_type' => 'free',
                        'shipping_cost' => '0',
                        'is_quantity_multiplied' => 0,
                        'est_shipping_days' => 28,
                        'num_of_sale' => 0,
                        'meta_title' => 'Saepe eum quo modi a',
                        'meta_description' => 'Sed quia quia perfer',
                        'meta_img' => '1',
                        'pdf' => NULL,
                        'slug' => 'serena-mccarty-y0hjy',
                        'rating' => 0.0,
                        'barcode' => NULL,
                        'digital' => 0,
                        'file_name' => NULL,
                        'file_path' => NULL,
                        'created_at' => '2021-04-08 12:23:15',
                        'updated_at' => '2021-04-08 13:37:30',
                    ),
                1 =>
                    array(
                        'id' => 2,
                        'name' => 'Kasper Hendricks',
                        'added_by' => 'seller',
                        'user_id' => 2,
                        'category_id' => 2,
                        'subcategory_id' => NULL,
                        'subsubcategory_id' => NULL,
                        'brand_id' => 2,
                        'photos' => NULL,
                        'thumbnail_img' => NULL,
                        'video_provider' => 'dailymotion',
                        'video_link' => NULL,
                        'tags' => '',
                        'description' => NULL,
                        'unit_price' => 655.0,
                        'purchase_price' => 131.0,
                        'variant_product' => 0,
                        'attributes' => '["1","2"]',
                        'choice_options' => '[{"attribute_id":"1","values":["11"]},{"attribute_id":"2","values":["Oak"]}]',
                        'colors' => '[]',
                        'variations' => NULL,
                        'todays_deal' => 0,
                        'published' => 1,
                        'stock_visibility_state' => 'quantity',
                        'cash_on_delivery' => 1,
                        'featured' => 0,
                        'seller_featured' => 0,
                        'current_stock' => 32,
                        'unit' => 'Aut quaerat commodi',
                        'min_qty' => 159,
                        'low_stock_quantity' => 46,
                        'discount' => 15.0,
                        'discount_type' => 'amount',
                        'tax' => NULL,
                        'tax_type' => NULL,
                        'shipping_type' => 'free',
                        'shipping_cost' => '0',
                        'is_quantity_multiplied' => 0,
                        'est_shipping_days' => 1,
                        'num_of_sale' => 0,
                        'meta_title' => 'Dolorem culpa solut',
                        'meta_description' => 'Ipsum aliquid exerc',
                        'meta_img' => NULL,
                        'pdf' => NULL,
                        'slug' => 'Kasper-Hendricks-H2Rxm',
                        'rating' => 0.0,
                        'barcode' => NULL,
                        'digital' => 0,
                        'file_name' => NULL,
                        'file_path' => NULL,
                        'created_at' => '2021-04-08 12:32:35',
                        'updated_at' => '2021-04-08 12:32:35',
                    ),
                2 =>
                    array(
                        'id' => 4,
                        'name' => 'Eim Solutions',
                        'added_by' => 'admin',
                        'user_id' => 1,
                        'category_id' => 3,
                        'subcategory_id' => NULL,
                        'subsubcategory_id' => NULL,
                        'brand_id' => 1,
                        'photos' => NULL,
                        'thumbnail_img' => '18',
                        'video_provider' => 'youtube',
                        'video_link' => NULL,
                        'tags' => 'it',
                        'description' => NULL,
                        'unit_price' => 1.0,
                        'purchase_price' => 2.0,
                        'variant_product' => 0,
                        'attributes' => '[]',
                        'choice_options' => '[]',
                        'colors' => '[]',
                        'variations' => NULL,
                        'todays_deal' => 1,
                        'published' => 1,
                        'stock_visibility_state' => 'quantity',
                        'cash_on_delivery' => 1,
                        'featured' => 1,
                        'seller_featured' => 0,
                        'current_stock' => 97,
                        'unit' => 'Company',
                        'min_qty' => 1,
                        'low_stock_quantity' => 1,
                        'discount' => 10.0,
                        'discount_type' => 'amount',
                        'tax' => NULL,
                        'tax_type' => NULL,
                        'shipping_type' => 'free',
                        'shipping_cost' => '0',
                        'is_quantity_multiplied' => 0,
                        'est_shipping_days' => NULL,
                        'num_of_sale' => 3,
                        'meta_title' => 'Eim Solutions',
                        'meta_description' => '',
                        'meta_img' => '17',
                        'pdf' => NULL,
                        'slug' => 'eim-solutions-fupav',
                        'rating' => 0.0,
                        'barcode' => NULL,
                        'digital' => 0,
                        'file_name' => NULL,
                        'file_path' => NULL,
                        'created_at' => '2021-04-08 13:56:28',
                        'updated_at' => '2021-04-09 20:35:25',
                    ),
            ));

        }
    }
}
