version: "3"
services:
  app2:
    build:
      context: ./docker/8.0-fpm
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: sail-8.0/app
    environment:
      WWWUSER: '${WWWUSER}'
      LARAVEL_SAIL: 1
    ports:
      - '9000:9000'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail2
    depends_on:
      - pgsql

  pgsql:
    image: 'postgres'
    ports:
      - '${DB_DOCKER_PORT_EXTERNAL:-5432}:5432'
    environment:
      PGUSER: '${DB_USERNAME:-postgres}'
      PGPASSWORD: '${DB_PASSWORD:-123456}'
      POSTGRES_DB: '${DB_DATABASE:-evsaas}'
      POSTGRES_USER: '${DB_USERNAME:-postgres}'
      POSTGRES_PASSWORD: '${DB_PASSWORD:-123456}'
    volumes:
      - 'sail2pgsql:/var/lib/postgresql/data'
    networks:
      - sail2

  cache:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - 'sail2redis:/data'
    networks:
      - sail2
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

  nginx:
    depends_on:
      - app2
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker/nginx/default-fpm-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/conf.d/
    networks:
      - sail2


#  cypress:
#    depends_on:
#      - nginx
#    image: cypress/included:7.6.0
#    volumes:
#      - .:/src/
#    environment:
#      - CYPRESS_BASE_URL=${CYPRESS_BASEURL}
#      - CYPRESS_RECORD_KEY=${CYPRESS_RECORDKEY}
#    working_dir: /src/
#    networks:
#      - sail2

networks:
  sail2:
    driver: bridge
volumes:
  sail2pgsql:
    driver: local
  sail2redis:
    driver: local
