version: "3.8"
services:
  db:
    image: mariadb:latest
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - '${DB_DOCKER_PORT_EXTERNAL:-3333}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD-rootpass}'
      MYSQL_DATABASE: '${DB_DATABASE-database}'
      MYSQL_USER: '${DB_PASSWORD-user}'
      MYSQL_PASSWORD: '${DB_PASSWORD-pass}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - type: volume
        source: dbdata
        target: /var/lib/mysql

  cache:
    image: redis:6.0.9-alpine

  app:
    user: "33:33"
    depends_on:
      - db
    image: jeankhawand/laradev:latest
    volumes:
      - .:/var/www/html/


  nginx:
    depends_on:
      - app
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www/html/
      - ./nginx:/etc/nginx/conf.d/
  cypress:
    depends_on:
      - nginx
    image: cypress/included:7.6.0
    volumes:
      - .:/src/
    environment:
      - CYPRESS_BASE_URL=${CYPRESS_BASEURL}
      - CYPRESS_RECORD_KEY=${CYPRESS_RECORDKEY}
    working_dir: /src/

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      - PMA_HOST=${DB_HOST}
      - PMA_PORT=${DB_PORT}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
      - PMA_ABSOLUTE_URI=${DB_PWA_URL}

volumes:
  dbdata:
    driver: local
