@include('frontend.layouts.global-partials.global-tailwind-config')
@include('frontend.layouts.global-partials.global-integrations')
@include('frontend.layouts.global-partials.global-styles')
@include('frontend.layouts.global-partials.global-alpine-custom-extensions')
@include('frontend.layouts.global-partials.global-fx')
@include('frontend.layouts.global-partials.global-editorjs-config')
